In [1]:
import sys
!{sys.executable} -m pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\karwi\appdata\local\programs\python\python313\lib\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in c:\users\karwi\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (2.4.3)
Requirement already satisfied: scipy>=1.10.0 in c:\users\karwi\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in c:\users\karwi\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\karwi\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (3.6.0)

[notice] A new release of pip is available: 24.3.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd
import matplotlib as pt
import sklearn

In [3]:
master_sheet = pd.read_csv("PAM ML Master Sheet.csv")

In [4]:
master_sheet.head(30)

,Test_id,Friction Reducer,Form,Charge Density (%),TDS,Boron (B),Barium (Ba+2),Calcium (Ca+2),Iron (Fe+2),Potassium (K+),...,300,250,200,150,100,50,25,12.5,0,R^2
0,1,A,CO_ePAM,32,5876,6.00,0.30,385.50,0.00,54.90,...,1.725,1.470,1.328,0.899,0.595,0.293,0.139,0.050,0.000,0.9800
1,2,A,CO_ePAM,32,164384,25.70,4.40,8908.00,0.00,1082.00,...,1.790,1.530,1.470,1.004,0.660,0.334,0.151,0.065,0.000,0.9500
2,3,A,CO_ePAM,32,89081,18.10,4.70,5255.00,0.00,469.80,...,1.802,1.514,1.414,0.952,0.644,0.323,0.169,0.077,0.000,0.9600
3,4,B,ePAM,30,11774,42.50,0.00,115.20,15.00,67.30,...,0.360,0.289,0.232,0.155,0.081,0.034,0.007,0.006,0.000,0.9900
4,5,B,ePAM,30,12993,36.40,0.00,158.80,12.70,55.70,...,0.517,0.423,0.348,0.275,0.154,0.085,0.027,0.016,0.000,0.9900
5,6,B,ePAM,30,15031,39.60,0.00,199.40,16.60,58.40,...,0.690,0.564,0.355,0.280,0.202,0.102,0.033,0.014,0.000,0.9400
6,7,C,Dry,30,12657,73.38,2.43,71.23,1.87,84.78,...,1.335,1.155,0.917,0.655,0.433,0.214,0.098,0.042,0.007,0.9977
7,8,C,Dry,30,15812,59.40,0.89,164.30,0.42,86.14,...,1.403,1.238,0.928,0.682,0.528,0.222,0.106,0.069,0.002,0.9953
8,9,C,Dry,30,102804,29.40,2.24,3259.00,0.16,299.80,...,1.067,0.828,0.648,0.461,0.312,0.157,0.077,0.038,0.009,0.9976
9,10,C,Dry,30,13069,87.74,0.52,102.30,1.45,76.14,...,1.390,1.121,0.881,0.660,0.418,0.193,0.084,0.030,0.002,0.9973
10,11,D,Slurry,30,23334,19.84,23.01,285.93,1.43,42.62,...,1.070,0.877,0.717,0.522,0.348,0.166,0.078,0.021,0.000,0.9986
11,12,D,Slurry,30,39767,16.59,107.82,366.25,3.73,99.48,...,1.248,1.147,1.032,0.644,0.409,0.197,0.107,0.036,0.000,0.9868
12,13,D,Slurry,30,16437,10.76,10.22,73.47,3.11,33.53,...,1.038,0.896,0.707,0.520,0.340,0.176,0.102,0.022,0.000,0.9994
13,14,E,Dry,30,4677,0.00,1.64,58.26,0.23,116.60,...,1.292,1.054,0.960,0.667,0.466,0.192,0.088,0.026,0.000,0.9921
14,15,F,ePAM,32,32176,0.00,77.75,545.20,0.00,117.90,...,1.689,1.512,1.111,0.818,0.527,0.296,0.147,0.055,0.000,0.9963
15,16,F,ePAM,32,67505,0.00,182.70,1323.00,0.00,318.10,...,2.070,1.885,1.439,0.952,0.665,0.301,0.146,0.056,0.000,0.9942
16,17,G,ePAM,30,141057,27.80,2.04,2273.00,0.70,623.00,...,1.656,1.398,1.147,0.873,0.587,0.289,0.139,0.049,0.000,0.9882
17,18,I,Dry,30,141057,27.80,2.04,2273.00,0.70,623.00,...,1.046,0.936,0.727,0.530,0.377,0.173,0.072,0.018,0.000,0.9914
18,19,G,ePAM,30,131855,28.00,2.02,1885.00,14.90,656.00,...,1.901,1.622,1.337,1.010,0.678,0.341,0.165,0.078,0.000,0.9821
19,20,I,Dry,30,131855,28.00,2.02,1885.00,14.90,656.00,...,1.204,1.007,0.818,0.626,0.403,0.188,0.077,0.023,0.000,0.9945
20,21,G,ePAM,30,140168,33.10,2.47,2375.00,10.50,722.00,...,1.775,1.462,1.219,0.942,0.619,0.312,0.144,0.057,0.000,0.9868
21,22,I,Dry,30,140168,33.10,2.47,2375.00,10.50,722.00,...,1.164,1.160,0.771,0.597,0.396,0.185,0.086,0.019,0.000,0.9753
22,23,H,ePAM,30,99684,86.07,6.99,2494.00,0.00,1099.00,...,1.320,1.032,0.846,0.689,0.419,0.188,0.085,0.016,0.000,0.9943
23,24,J,Dry,30,111746,73.34,8.11,3816.00,0.00,714.90,...,1.225,1.072,0.853,0.596,0.483,0.188,0.088,0.031,0.000,0.9960
24,25,K,CO_ePAM,26,51504,44.78,310.80,201.90,0.00,315.00,...,0.872,0.728,0.595,0.438,0.301,0.144,0.055,0.014,0.000,0.9976
25,26,L,Dry,30,51504,44.78,310.80,201.90,0.00,315.00,...,1.301,1.089,0.910,0.663,0.436,0.213,0.094,0.032,0.000,0.9945
26,27,M,ePAM,30,245,0.00,0.00,31.69,0.09,3.73,...,2.046,1.778,1.479,1.083,0.719,0.351,0.168,0.060,0.000,0.9976
27,28,N,ePAM,30,245,0.00,0.00,31.69,0.09,3.73,...,1.718,1.436,1.157,0.890,0.566,0.276,0.123,0.041,0.000,0.9994
28,29,C,Dry,30,245,0.00,0.00,31.69,0.09,3.73,...,1.494,1.165,0.949,0.680,0.434,0.210,0.109,0.036,0.000,0.9938
29,30,O,Dry,30,1113,0.00,0.00,122.70,0.00,5.43,...,1.023,0.875,0.686,0.553,0.366,0.193,0.116,0.099,0.000,0.9904

In [5]:
master_sheet.dtypes

Test_id                   int64
Friction Reducer            str
Form                        str
Charge Density (%)        int64
TDS                       int64
Boron (B)               float64
Barium (Ba+2)           float64
Calcium (Ca+2)          float64
Iron (Fe+2)             float64
Potassium (K+)          float64
Magnesium (Mg+2)        float64
Manganese (Mn+2)        float64
Sodium (Na+)            float64
Strontium (Sr+2)        float64
Zinc (Zn+2)             float64
Fluoride (F⁻)           float64
Chlorides (Cl-)         float64
Nitrite (NO₂⁻)          float64
Bromide (Br⁻)           float64
Nitrate (NO₃⁻)          float64
Phosphate (PO₄³⁻)       float64
Sulfate (SO4-2)         float64
Bicarbonates (HCO3-)    float64
Carbonates (CO3-2)      float64
DR (R+)                 float64
500                     float64
300                     float64
250                     float64
200                     float64
150                     float64
100                     float64
50                      float64
25                      float64
12.5                    float64
0                       float64
R^2                     float64
dtype: object

In [6]:
numeric_cols =['TDS','Boron (B)', 'Barium (Ba+2)',	'Calcium (Ca+2)','Iron (Fe+2)','Potassium (K+)','Magnesium (Mg+2)','Manganese (Mn+2)','Strontium (Sr+2)','Zinc (Zn+2)', 'Bromide (Br⁻)','Sulfate (SO4-2)', '500','300',	'250', '200',	'150',	'100',	'50',	'25',	'12,5',	'0', 'R^2']
for col in numeric_cols:
    master_sheet[col] = master_sheet[col].str.replace(',','.')

AttributeError: Can only use .str accessor with string values, not integer

In [ ]:
numeric_cols = ['Charge Density (%)',
                'TDS','Boron (B)', 'Barium (Ba+2)',	'Calcium (Ca+2)','Iron (Fe+2)','Potassium (K+)','Magnesium (Mg+2)','Manganese (Mn+2)','Sodium (Na+)','Strontium (Sr+2)','Zinc (Zn+2)','Fluoride (F⁻)', 'Chlorides (Cl-)', 'Nitrite (NO₂⁻)', 'Bromide (Br⁻)', 'Nitrate (NO₃⁻)', 'Phosphate (PO₄³⁻)', 'Sulfate (SO4-2)', 'Bicarbonates (HCO3-)', '500','300',	'250', '200',	'150',	'100',	'50',	'25',	'12,5',	'0', 'R^2']
for col in numeric_cols:
    master_sheet[col] = pd.to_numeric(master_sheet[col], errors='coerce')

KeyError: '12,5'

In [7]:
master_sheet.info()

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 36 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Test_id               40 non-null     int64
 1   Friction Reducer      40 non-null     str
 2   Form                  40 non-null     str
 3   Charge Density (%)    40 non-null     int64
 4   TDS                   40 non-null     int64
 5   Boron (B)             40 non-null     float64
 6   Barium (Ba+2)         40 non-null     float64
 7   Calcium (Ca+2)        40 non-null     float64
 8   Iron (Fe+2)           40 non-null     float64
 9   Potassium (K+)        40 non-null     float64
 10  Magnesium (Mg+2)      40 non-null     float64
 11  Manganese (Mn+2)      40 non-null     float64
 12  Sodium (Na+)          40 non-null     float64
 13  Strontium (Sr+2)      40 non-null     float64
 14  Zinc (Zn+2)           40 non-null     float64
 15  Fluoride (F⁻)         40 non-null     float64
 16  Chlorides (Cl-)       40 non-null     float64
 17  Nitrite (NO₂⁻)        40 non-null     float64
 18  Bromide (Br⁻)         40 non-null     float64
 19  Nitrate (NO₃⁻)        40 non-null     float64
 20  Phosphate (PO₄³⁻)     40 non-null     float64
 21  Sulfate (SO4-2)       40 non-null     float64
 22  Bicarbonates (HCO3-)  40 non-null     float64
 23  Carbonates (CO3-2)    40 non-null     float64
 24  DR (R+)               40 non-null     float64
 25  500                   40 non-null     float64
 26  300                   40 non-null     float64
 27  250                   40 non-null     float64
 28  200                   40 non-null     float64
 29  150                   40 non-null     float64
 30  100                   40 non-null     float64
 31  50                    40 non-null     float64
 32  25                    40 non-null     float64
 33  12.5                  40 non-null     float64
 34  0                     40 non-null     float64
 35  R^2                   40 non-null     float64
dtypes: float64(31), int64(3), str(2)
memory usage: 11.4 KB

In [8]:
master_sheet.head(10)

,Test_id,Friction Reducer,Form,Charge Density (%),TDS,Boron (B),Barium (Ba+2),Calcium (Ca+2),Iron (Fe+2),Potassium (K+),...,300,250,200,150,100,50,25,12.5,0,R^2
0,1,A,CO_ePAM,32,5876,6.00,0.30,385.50,0.00,54.90,...,1.725,1.470,1.328,0.899,0.595,0.293,0.139,0.050,0.000,0.9800
1,2,A,CO_ePAM,32,164384,25.70,4.40,8908.00,0.00,1082.00,...,1.790,1.530,1.470,1.004,0.660,0.334,0.151,0.065,0.000,0.9500
2,3,A,CO_ePAM,32,89081,18.10,4.70,5255.00,0.00,469.80,...,1.802,1.514,1.414,0.952,0.644,0.323,0.169,0.077,0.000,0.9600
3,4,B,ePAM,30,11774,42.50,0.00,115.20,15.00,67.30,...,0.360,0.289,0.232,0.155,0.081,0.034,0.007,0.006,0.000,0.9900
4,5,B,ePAM,30,12993,36.40,0.00,158.80,12.70,55.70,...,0.517,0.423,0.348,0.275,0.154,0.085,0.027,0.016,0.000,0.9900
5,6,B,ePAM,30,15031,39.60,0.00,199.40,16.60,58.40,...,0.690,0.564,0.355,0.280,0.202,0.102,0.033,0.014,0.000,0.9400
6,7,C,Dry,30,12657,73.38,2.43,71.23,1.87,84.78,...,1.335,1.155,0.917,0.655,0.433,0.214,0.098,0.042,0.007,0.9977
7,8,C,Dry,30,15812,59.40,0.89,164.30,0.42,86.14,...,1.403,1.238,0.928,0.682,0.528,0.222,0.106,0.069,0.002,0.9953
8,9,C,Dry,30,102804,29.40,2.24,3259.00,0.16,299.80,...,1.067,0.828,0.648,0.461,0.312,0.157,0.077,0.038,0.009,0.9976
9,10,C,Dry,30,13069,87.74,0.52,102.30,1.45,76.14,...,1.390,1.121,0.881,0.660,0.418,0.193,0.084,0.030,0.002,0.9973

In [9]:
master_sheet.notna().value_counts()

Test_id  Friction Reducer  Form  Charge Density (%)  TDS   Boron (B)  Barium (Ba+2)  Calcium (Ca+2)  Iron (Fe+2)  Potassium (K+)  Magnesium (Mg+2)  Manganese (Mn+2)  Sodium (Na+)  Strontium (Sr+2)  Zinc (Zn+2)  Fluoride (F⁻)  Chlorides (Cl-)  Nitrite (NO₂⁻)  Bromide (Br⁻)  Nitrate (NO₃⁻)  Phosphate (PO₄³⁻)  Sulfate (SO4-2)  Bicarbonates (HCO3-)  Carbonates (CO3-2)  DR (R+)  500   300   250   200   150   100   50    25    12.5  0     R^2
True     True              True  True                True  True       True           True            True         True            True              True              True          True              True         True           True             True            True           True            True               True             True                  True                True     True  True  True  True  True  True  True  True  True  True  True    40
Name: count, dtype: int64

# Model A (3 entires - proof of concept)

In [10]:
from sklearn.linear_model import LinearRegression

In [11]:
model = LinearRegression()

In [12]:
feature_columns =  master_sheet[["TDS", "Boron (B)", "Barium (Ba+2)", "Calcium (Ca+2)",	"Iron (Fe+2)", "Potassium (K+)", "Magnesium (Mg+2)", "Manganese (Mn+2)", "Sodium (Na+)", "Strontium (Sr+2)", "Zinc (Zn+2)", "Fluoride (F⁻)", "Chlorides (Cl-)",	"Nitrite (NO₂⁻)", "Bromide (Br⁻)", "Nitrate (NO₃⁻)", "Phosphate (PO₄³⁻)", "Sulfate (SO4-2)", "Bicarbonates (HCO3-)", "DR (R+)"]]

In [13]:
feature_columns.head(6)

,TDS,Boron (B),Barium (Ba+2),Calcium (Ca+2),Iron (Fe+2),Potassium (K+),Magnesium (Mg+2),Manganese (Mn+2),Sodium (Na+),Strontium (Sr+2),Zinc (Zn+2),Fluoride (F⁻),Chlorides (Cl-),Nitrite (NO₂⁻),Bromide (Br⁻),Nitrate (NO₃⁻),Phosphate (PO₄³⁻),Sulfate (SO4-2),Bicarbonates (HCO3-),DR (R+)
0,5876,6.0,0.3,385.5,0.0,54.9,89.1,0.1,1527.0,10.7,0.46,0.0,2855.0,0.0,26.2,0.0,0.0,904.7,17.0,0.17
1,164384,25.7,4.4,8908.0,0.0,1082.0,940.4,0.0,54790.0,279.8,0.43,0.0,96414.0,0.0,419.4,0.0,0.0,1151.9,369.0,0.12
2,89081,18.1,4.7,5255.0,0.0,469.8,549.3,0.0,25960.0,116.5,0.63,0.0,54754.0,0.0,280.1,0.0,0.0,1304.2,369.0,0.10
3,11774,42.5,0.0,115.2,15.0,67.3,20.9,0.7,39587.0,11.5,0.00,0.0,5518.5,0.0,154.8,0.0,0.0,593.6,1276.0,0.02
4,12993,36.4,0.0,158.8,12.7,55.7,25.8,0.7,44211.0,13.6,0.00,0.0,6381.4,0.0,180.4,0.0,0.0,549.5,1157.0,0.03
5,15031,39.6,0.0,199.4,16.6,58.4,28.8,0.8,50428.0,14.5,0.00,0.0,7647.5,0.0,216.0,0.0,0.0,592.0,1174.6,0.03

In [14]:
target_columns = master_sheet[["500", "300", "250", "200", "150", "100", "50", "25", "12.5", "0"]]

In [15]:
target_columns.head()
target_columns.shape

(40, 10)

In [16]:
X_train = feature_columns.loc[(feature_columns['TDS'] == 5876.0	) | (feature_columns['TDS']==164384.0)]

In [17]:
Y_train = target_columns.loc[X_train.index]

In [18]:
Y_train.head()

     500    300   250    200    150    100     50     25   12.5    0
0  2.447  1.725  1.47  1.328  0.899  0.595  0.293  0.139  0.050  0.0
1  2.381  1.790  1.53  1.470  1.004  0.660  0.334  0.151  0.065  0.0

In [19]:
X_test = feature_columns.loc[(feature_columns['TDS'] == 89081.0)]
Y_test = target_columns.loc[X_test.index]

In [20]:
reg = model.fit(X_train, Y_train)

reg.score(X_train,Y_train)

1.0

In [21]:
Y_pred = model.predict(X_test)

In [22]:
print(Y_pred)

[[2.41221787 1.75925513 1.50162012 1.40283428 0.95433521 0.62925513
  0.31460708 0.14532402 0.05790503 0.        ]]

In [23]:
Y_test.head()

   500    300    250    200    150    100     50     25   12.5    0
2  2.0  1.802  1.514  1.414  0.952  0.644  0.323  0.169  0.077  0.0

# Model B (removed 500 ppm variable)

In [24]:
model_b = master_sheet

In [25]:
model_b.drop(columns=['500'])
model_b.dropna(inplace=True)

In [26]:
feature_columns =  model_b[["TDS", "Boron (B)", "Barium (Ba+2)", "Calcium (Ca+2)",	"Iron (Fe+2)", "Potassium (K+)", "Magnesium (Mg+2)", "Manganese (Mn+2)", "Sodium (Na+)", "Strontium (Sr+2)", "Zinc (Zn+2)", "Fluoride (F⁻)", "Chlorides (Cl-)",	"Nitrite (NO₂⁻)", "Bromide (Br⁻)", "Nitrate (NO₃⁻)", "Phosphate (PO₄³⁻)", "Sulfate (SO4-2)", "Bicarbonates (HCO3-)"]]

In [27]:
target_columns = model_b[["300", "250", "200", "150", "100", "50", "25", "12.5", "0"]]

In [28]:
X_train = feature_columns.loc[(feature_columns['TDS'] == 5876.0	) | (feature_columns['TDS']==164384.0)]

In [29]:
Y_train = target_columns.loc[X_train.index]

In [30]:
X_test = feature_columns.loc[(feature_columns['TDS'] == 89081.0)]

In [31]:
Y_test = target_columns.loc[X_test.index]

In [32]:
reg = model.fit(X_train, Y_train)
reg.score(X_train, Y_train)

1.0

In [33]:
Y_pred = model.predict(X_test)

In [34]:
print(Y_pred)

[[1.75925513 1.50162012 1.40283428 0.95433521 0.62925513 0.31460708
  0.14532402 0.05790503 0.        ]]

### Insight:
A preliminary multi-output linear regression model was trained using standard curve data from two brines (5k and 164k TDS) and tested against an intermediate brine (~89k TDS). The model successfully reproduced the overall shape of the standard curve and generated absorbance predictions that were generally close to the observed values. The largest deviation occurred at the 500 ppm calibration point, which is also associated with reduced standard curve linearity (R² < 0.99) in laboratory measurements. Removing the 500 ppm point improved standard curve performance and suggests that the upper calibration range may contribute disproportionate variability.

# Model A (14 Entries)

In [35]:
from sklearn.preprocessing import OneHotEncoder

In [36]:
master_sheet.head(15)

,Test_id,Friction Reducer,Form,Charge Density (%),TDS,Boron (B),Barium (Ba+2),Calcium (Ca+2),Iron (Fe+2),Potassium (K+),...,300,250,200,150,100,50,25,12.5,0,R^2
0,1,A,CO_ePAM,32,5876,6.00,0.30,385.50,0.00,54.90,...,1.725,1.470,1.328,0.899,0.595,0.293,0.139,0.050,0.000,0.9800
1,2,A,CO_ePAM,32,164384,25.70,4.40,8908.00,0.00,1082.00,...,1.790,1.530,1.470,1.004,0.660,0.334,0.151,0.065,0.000,0.9500
2,3,A,CO_ePAM,32,89081,18.10,4.70,5255.00,0.00,469.80,...,1.802,1.514,1.414,0.952,0.644,0.323,0.169,0.077,0.000,0.9600
3,4,B,ePAM,30,11774,42.50,0.00,115.20,15.00,67.30,...,0.360,0.289,0.232,0.155,0.081,0.034,0.007,0.006,0.000,0.9900
4,5,B,ePAM,30,12993,36.40,0.00,158.80,12.70,55.70,...,0.517,0.423,0.348,0.275,0.154,0.085,0.027,0.016,0.000,0.9900
5,6,B,ePAM,30,15031,39.60,0.00,199.40,16.60,58.40,...,0.690,0.564,0.355,0.280,0.202,0.102,0.033,0.014,0.000,0.9400
6,7,C,Dry,30,12657,73.38,2.43,71.23,1.87,84.78,...,1.335,1.155,0.917,0.655,0.433,0.214,0.098,0.042,0.007,0.9977
7,8,C,Dry,30,15812,59.40,0.89,164.30,0.42,86.14,...,1.403,1.238,0.928,0.682,0.528,0.222,0.106,0.069,0.002,0.9953
8,9,C,Dry,30,102804,29.40,2.24,3259.00,0.16,299.80,...,1.067,0.828,0.648,0.461,0.312,0.157,0.077,0.038,0.009,0.9976
9,10,C,Dry,30,13069,87.74,0.52,102.30,1.45,76.14,...,1.390,1.121,0.881,0.660,0.418,0.193,0.084,0.030,0.002,0.9973
10,11,D,Slurry,30,23334,19.84,23.01,285.93,1.43,42.62,...,1.070,0.877,0.717,0.522,0.348,0.166,0.078,0.021,0.000,0.9986
11,12,D,Slurry,30,39767,16.59,107.82,366.25,3.73,99.48,...,1.248,1.147,1.032,0.644,0.409,0.197,0.107,0.036,0.000,0.9868
12,13,D,Slurry,30,16437,10.76,10.22,73.47,3.11,33.53,...,1.038,0.896,0.707,0.520,0.340,0.176,0.102,0.022,0.000,0.9994
13,14,E,Dry,30,4677,0.00,1.64,58.26,0.23,116.60,...,1.292,1.054,0.960,0.667,0.466,0.192,0.088,0.026,0.000,0.9921
14,15,F,ePAM,32,32176,0.00,77.75,545.20,0.00,117.90,...,1.689,1.512,1.111,0.818,0.527,0.296,0.147,0.055,0.000,0.9963

In [37]:
master_sheet.dropna()

,Test_id,Friction Reducer,Form,Charge Density (%),TDS,Boron (B),Barium (Ba+2),Calcium (Ca+2),Iron (Fe+2),Potassium (K+),...,300,250,200,150,100,50,25,12.5,0,R^2
0,1,A,CO_ePAM,32,5876,6.00,0.30,385.50,0.00,54.90,...,1.725,1.470,1.328,0.899,0.5950,0.293,0.139,0.050,0.000,0.9800
1,2,A,CO_ePAM,32,164384,25.70,4.40,8908.00,0.00,1082.00,...,1.790,1.530,1.470,1.004,0.6600,0.334,0.151,0.065,0.000,0.9500
2,3,A,CO_ePAM,32,89081,18.10,4.70,5255.00,0.00,469.80,...,1.802,1.514,1.414,0.952,0.6440,0.323,0.169,0.077,0.000,0.9600
3,4,B,ePAM,30,11774,42.50,0.00,115.20,15.00,67.30,...,0.360,0.289,0.232,0.155,0.0810,0.034,0.007,0.006,0.000,0.9900
4,5,B,ePAM,30,12993,36.40,0.00,158.80,12.70,55.70,...,0.517,0.423,0.348,0.275,0.1540,0.085,0.027,0.016,0.000,0.9900
5,6,B,ePAM,30,15031,39.60,0.00,199.40,16.60,58.40,...,0.690,0.564,0.355,0.280,0.2020,0.102,0.033,0.014,0.000,0.9400
6,7,C,Dry,30,12657,73.38,2.43,71.23,1.87,84.78,...,1.335,1.155,0.917,0.655,0.4330,0.214,0.098,0.042,0.007,0.9977
7,8,C,Dry,30,15812,59.40,0.89,164.30,0.42,86.14,...,1.403,1.238,0.928,0.682,0.5280,0.222,0.106,0.069,0.002,0.9953
8,9,C,Dry,30,102804,29.40,2.24,3259.00,0.16,299.80,...,1.067,0.828,0.648,0.461,0.3120,0.157,0.077,0.038,0.009,0.9976
9,10,C,Dry,30,13069,87.74,0.52,102.30,1.45,76.14,...,1.390,1.121,0.881,0.660,0.4180,0.193,0.084,0.030,0.002,0.9973
10,11,D,Slurry,30,23334,19.84,23.01,285.93,1.43,42.62,...,1.070,0.877,0.717,0.522,0.3480,0.166,0.078,0.021,0.000,0.9986
11,12,D,Slurry,30,39767,16.59,107.82,366.25,3.73,99.48,...,1.248,1.147,1.032,0.644,0.4090,0.197,0.107,0.036,0.000,0.9868
12,13,D,Slurry,30,16437,10.76,10.22,73.47,3.11,33.53,...,1.038,0.896,0.707,0.520,0.3400,0.176,0.102,0.022,0.000,0.9994
13,14,E,Dry,30,4677,0.00,1.64,58.26,0.23,116.60,...,1.292,1.054,0.960,0.667,0.4660,0.192,0.088,0.026,0.000,0.9921
14,15,F,ePAM,32,32176,0.00,77.75,545.20,0.00,117.90,...,1.689,1.512,1.111,0.818,0.5270,0.296,0.147,0.055,0.000,0.9963
15,16,F,ePAM,32,67505,0.00,182.70,1323.00,0.00,318.10,...,2.070,1.885,1.439,0.952,0.6650,0.301,0.146,0.056,0.000,0.9942
16,17,G,ePAM,30,141057,27.80,2.04,2273.00,0.70,623.00,...,1.656,1.398,1.147,0.873,0.5870,0.289,0.139,0.049,0.000,0.9882
17,18,I,Dry,30,141057,27.80,2.04,2273.00,0.70,623.00,...,1.046,0.936,0.727,0.530,0.3770,0.173,0.072,0.018,0.000,0.9914
18,19,G,ePAM,30,131855,28.00,2.02,1885.00,14.90,656.00,...,1.901,1.622,1.337,1.010,0.6780,0.341,0.165,0.078,0.000,0.9821
19,20,I,Dry,30,131855,28.00,2.02,1885.00,14.90,656.00,...,1.204,1.007,0.818,0.626,0.4030,0.188,0.077,0.023,0.000,0.9945
20,21,G,ePAM,30,140168,33.10,2.47,2375.00,10.50,722.00,...,1.775,1.462,1.219,0.942,0.6190,0.312,0.144,0.057,0.000,0.9868
21,22,I,Dry,30,140168,33.10,2.47,2375.00,10.50,722.00,...,1.164,1.160,0.771,0.597,0.3960,0.185,0.086,0.019,0.000,0.9753
22,23,H,ePAM,30,99684,86.07,6.99,2494.00,0.00,1099.00,...,1.320,1.032,0.846,0.689,0.4190,0.188,0.085,0.016,0.000,0.9943
23,24,J,Dry,30,111746,73.34,8.11,3816.00,0.00,714.90,...,1.225,1.072,0.853,0.596,0.4830,0.188,0.088,0.031,0.000,0.9960
24,25,K,CO_ePAM,26,51504,44.78,310.80,201.90,0.00,315.00,...,0.872,0.728,0.595,0.438,0.3010,0.144,0.055,0.014,0.000,0.9976
25,26,L,Dry,30,51504,44.78,310.80,201.90,0.00,315.00,...,1.301,1.089,0.910,0.663,0.4360,0.213,0.094,0.032,0.000,0.9945
26,27,M,ePAM,30,245,0.00,0.00,31.69,0.09,3.73,...,2.046,1.778,1.479,1.083,0.7190,0.351,0.168,0.060,0.000,0.9976
27,28,N,ePAM,30,245,0.00,0.00,31.69,0.09,3.73,...,1.718,1.436,1.157,0.890,0.5660,0.276,0.123,0.041,0.000,0.9994
28,29,C,Dry,30,245,0.00,0.00,31.69,0.09,3.73,...,1.494,1.165,0.949,0.680,0.4340,0.210,0.109,0.036,0.000,0.9938
29,30,O,Dry,30,1113,0.00,0.00,122.70,0.00,5.43,...,1.023,0.875,0.686,0.553,0.3660,0.193,0.116,0.099,0.000,0.9904
30,31,O,Dry,30,10366,9.70,1.49,214.30,69.30,30.56,...,1.104,0.942,0.816,0.623,0.3750,0.189,0.089,0.044,0.000,0.9957
31,32,O,Dry,30,28245,19.45,18.22,370.70,1.08,73.52,...,1.356,1.111,0.910,0.666,0.4160,0.197,0.098,0.027,0.000,0.9958
32,33,C,Dry,30,5,0.00,0.00,0.00,0.00,0.00,...,1.208,1.097,0.850,0.685,0.4220,0.195,0.081,0.019,0.000,0.9971
33,34,P,Dry,30,5,0.00,0.00,0.00,0.00,0.00,...,1.487,1.239,1.030,0.758,0.4665,0.244,0.151,0.083,0.000,0.9900
34,35,Q,ePAM,30,167025,0.00,0.00,3547.33,0.00,677.58,...,1.631,1.475,1.209,0.896,0.6230,0.285,0.146,0.070,0.000,0.9881
35,36,Q,ePAM,30,119141,0.00,0.00,2516.00,0.00,447.80,...,1.662,1.388,1.150,0.835,0.5660,0.303,0.127,0.065,0.000,0.9873
36,37,Q,ePAM,30,42320,0.00,0.00,1035.00,0.00,180.30,...,1.502,1.422,1.195,0.812,0.5820,0.311,0.151,0.071,0.000,0.9927
37,38,R,CO_ePAM,30,42320,0.00,0.00,1035.00,0.00,180.30,...,1.660,1.378,1.114,0.835,0.5450,0.277,0.123,0.041,0.000,0.9915
38,39,E,Dry,30,9976,16.15,1.75,45.26,1.35,37.11,...,1.404,1.324,1.048,0.779,0.4900,0.238,0.073,0.064,0.000,0.9867
39,40,Q,ePAM,30,152262,27.13,0.00,2606.50,0.00,659.55,...,1.657,1.423,1.160,0.874,0.6010,0.268,0.126,0.050,0.000,0.9858

In [38]:
categorical_columns = master_sheet.select_dtypes(include=['object']).columns
encoder = OneHotEncoder(sparse_output=False)
encoded_data = encoder.fit_transform(master_sheet[categorical_columns])
encoded_df = pd.DataFrame(encoded_data,
                          columns=encoder.get_feature_names_out(categorical_columns))
final_df = pd.concat([master_sheet.drop(columns=categorical_columns), encoded_df], axis = 1)

C:\Users\Karwi\AppData\Local\Temp\ipykernel_6960\2882799231.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = master_sheet.select_dtypes(include=['object']).columns

In [39]:
final_df.head(15)

,Test_id,Charge Density (%),TDS,Boron (B),Barium (Ba+2),Calcium (Ca+2),Iron (Fe+2),Potassium (K+),Magnesium (Mg+2),Manganese (Mn+2),...,Friction Reducer_M,Friction Reducer_N,Friction Reducer_O,Friction Reducer_P,Friction Reducer_Q,Friction Reducer_R,Form_CO_ePAM,Form_Dry,Form_Slurry,Form_ePAM
0,1,32,5876,6.00,0.30,385.50,0.00,54.90,89.10,0.10,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,2,32,164384,25.70,4.40,8908.00,0.00,1082.00,940.40,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,3,32,89081,18.10,4.70,5255.00,0.00,469.80,549.30,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,4,30,11774,42.50,0.00,115.20,15.00,67.30,20.90,0.70,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,5,30,12993,36.40,0.00,158.80,12.70,55.70,25.80,0.70,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
5,6,30,15031,39.60,0.00,199.40,16.60,58.40,28.80,0.80,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
6,7,30,12657,73.38,2.43,71.23,1.87,84.78,16.99,0.30,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
7,8,30,15812,59.40,0.89,164.30,0.42,86.14,27.48,0.50,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
8,9,30,102804,29.40,2.24,3259.00,0.16,299.80,587.00,2.26,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
9,10,30,13069,87.74,0.52,102.30,1.45,76.14,14.12,0.07,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
10,11,30,23334,19.84,23.01,285.93,1.43,42.62,41.35,0.38,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
11,12,30,39767,16.59,107.82,366.25,3.73,99.48,78.22,0.52,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
12,13,30,16437,10.76,10.22,73.47,3.11,33.53,15.78,0.09,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
13,14,30,4677,0.00,1.64,58.26,0.23,116.60,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
14,15,32,32176,0.00,77.75,545.20,0.00,117.90,55.32,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [40]:
final_df.dropna(inplace=True)

In [41]:
final_df.drop(columns=['Friction Reducer_15,812', 'Friction Reducer_nan', 'Form_nan'], errors='ignore')

,Test_id,Charge Density (%),TDS,Boron (B),Barium (Ba+2),Calcium (Ca+2),Iron (Fe+2),Potassium (K+),Magnesium (Mg+2),Manganese (Mn+2),...,Friction Reducer_M,Friction Reducer_N,Friction Reducer_O,Friction Reducer_P,Friction Reducer_Q,Friction Reducer_R,Form_CO_ePAM,Form_Dry,Form_Slurry,Form_ePAM
0,1,32,5876,6.00,0.30,385.50,0.00,54.90,89.10,0.10,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,2,32,164384,25.70,4.40,8908.00,0.00,1082.00,940.40,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,3,32,89081,18.10,4.70,5255.00,0.00,469.80,549.30,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,4,30,11774,42.50,0.00,115.20,15.00,67.30,20.90,0.70,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,5,30,12993,36.40,0.00,158.80,12.70,55.70,25.80,0.70,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
5,6,30,15031,39.60,0.00,199.40,16.60,58.40,28.80,0.80,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
6,7,30,12657,73.38,2.43,71.23,1.87,84.78,16.99,0.30,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
7,8,30,15812,59.40,0.89,164.30,0.42,86.14,27.48,0.50,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
8,9,30,102804,29.40,2.24,3259.00,0.16,299.80,587.00,2.26,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
9,10,30,13069,87.74,0.52,102.30,1.45,76.14,14.12,0.07,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
10,11,30,23334,19.84,23.01,285.93,1.43,42.62,41.35,0.38,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
11,12,30,39767,16.59,107.82,366.25,3.73,99.48,78.22,0.52,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
12,13,30,16437,10.76,10.22,73.47,3.11,33.53,15.78,0.09,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
13,14,30,4677,0.00,1.64,58.26,0.23,116.60,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
14,15,32,32176,0.00,77.75,545.20,0.00,117.90,55.32,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
15,16,32,67505,0.00,182.70,1323.00,0.00,318.10,150.10,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
16,17,30,141057,27.80,2.04,2273.00,0.70,623.00,406.00,0.53,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
17,18,30,141057,27.80,2.04,2273.00,0.70,623.00,406.00,0.53,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
18,19,30,131855,28.00,2.02,1885.00,14.90,656.00,370.00,0.77,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
19,20,30,131855,28.00,2.02,1885.00,14.90,656.00,370.00,0.77,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
20,21,30,140168,33.10,2.47,2375.00,10.50,722.00,464.00,0.72,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
21,22,30,140168,33.10,2.47,2375.00,10.50,722.00,464.00,0.72,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
22,23,30,99684,86.07,6.99,2494.00,0.00,1099.00,401.30,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
23,24,30,111746,73.34,8.11,3816.00,0.00,714.90,400.90,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
24,25,26,51504,44.78,310.80,201.90,0.00,315.00,66.19,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
25,26,30,51504,44.78,310.80,201.90,0.00,315.00,66.19,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
26,27,30,245,0.00,0.00,31.69,0.09,3.73,3.04,0.00,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
27,28,30,245,0.00,0.00,31.69,0.09,3.73,3.04,0.00,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
28,29,30,245,0.00,0.00,31.69,0.09,3.73,3.04,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
29,30,30,1113,0.00,0.00,122.70,0.00,5.43,32.65,1.17,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
30,31,30,10366,9.70,1.49,214.30,69.30,30.56,37.81,2.06,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
31,32,30,28245,19.45,18.22,370.70,1.08,73.52,62.41,0.28,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
32,33,30,5,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
33,34,30,5,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
34,35,30,167025,0.00,0.00,3547.33,0.00,677.58,548.13,0.00,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
35,36,30,119141,0.00,0.00,2516.00,0.00,447.80,416.20,0.00,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
36,37,30,42320,0.00,0.00,1035.00,0.00,180.30,178.30,0.00,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
37,38,30,42320,0.00,0.00,1035.00,0.00,180.30,178.30,0.00,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
38,39,30,9976,16.15,1.75,45.26,1.35,37.11,6.36,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
39,40,30,152262,27.13,0.00,2606.50,0.00,659.55,436.75,0.00,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0

In [42]:
fr_test = final_df['Friction Reducer_C'] == 1
fr_train= (final_df[(final_df['Friction Reducer_A'] == 1) | (final_df['Friction Reducer_B'] == 1)])

In [43]:
fr_test.head()

0    False
1    False
2    False
3    False
4    False
Name: Friction Reducer_C, dtype: bool

In [44]:
feature_columns = fr_train[["Charge Density (%)", "Boron (B)", "Barium (Ba+2)", "Calcium (Ca+2)",	"Iron (Fe+2)", "Potassium (K+)", "Magnesium (Mg+2)", "Manganese (Mn+2)", "Sodium (Na+)", "Strontium (Sr+2)", "Zinc (Zn+2)", "Fluoride (F⁻)", "Chlorides (Cl-)",	"Nitrite (NO₂⁻)", "Bromide (Br⁻)", "Nitrate (NO₃⁻)", "Phosphate (PO₄³⁻)", "Sulfate (SO4-2)", "Bicarbonates (HCO3-)", "Friction Reducer_A", "Friction Reducer_B", "Friction Reducer_C", "Form_CO_ePAM", "Form_Dry", "Form_ePAM"]]

In [45]:
feature_columns.head(10)

,Charge Density (%),Boron (B),Barium (Ba+2),Calcium (Ca+2),Iron (Fe+2),Potassium (K+),Magnesium (Mg+2),Manganese (Mn+2),Sodium (Na+),Strontium (Sr+2),...,Nitrate (NO₃⁻),Phosphate (PO₄³⁻),Sulfate (SO4-2),Bicarbonates (HCO3-),Friction Reducer_A,Friction Reducer_B,Friction Reducer_C,Form_CO_ePAM,Form_Dry,Form_ePAM
0,32,6.0,0.3,385.5,0.0,54.9,89.1,0.1,1527.0,10.7,...,0.0,0.0,904.7,17.0,1.0,0.0,0.0,1.0,0.0,0.0
1,32,25.7,4.4,8908.0,0.0,1082.0,940.4,0.0,54790.0,279.8,...,0.0,0.0,1151.9,369.0,1.0,0.0,0.0,1.0,0.0,0.0
2,32,18.1,4.7,5255.0,0.0,469.8,549.3,0.0,25960.0,116.5,...,0.0,0.0,1304.2,369.0,1.0,0.0,0.0,1.0,0.0,0.0
3,30,42.5,0.0,115.2,15.0,67.3,20.9,0.7,39587.0,11.5,...,0.0,0.0,593.6,1276.0,0.0,1.0,0.0,0.0,0.0,1.0
4,30,36.4,0.0,158.8,12.7,55.7,25.8,0.7,44211.0,13.6,...,0.0,0.0,549.5,1157.0,0.0,1.0,0.0,0.0,0.0,1.0
5,30,39.6,0.0,199.4,16.6,58.4,28.8,0.8,50428.0,14.5,...,0.0,0.0,592.0,1174.6,0.0,1.0,0.0,0.0,0.0,1.0

In [46]:
target_columns = fr_train[['500', '300', '250', '200', '150', '100', '50', '25', '12.5', '0']]

In [47]:
target_columns.head(7)

     500    300    250    200    150    100     50     25   12.5    0
0  2.447  1.725  1.470  1.328  0.899  0.595  0.293  0.139  0.050  0.0
1  2.381  1.790  1.530  1.470  1.004  0.660  0.334  0.151  0.065  0.0
2  2.000  1.802  1.514  1.414  0.952  0.644  0.323  0.169  0.077  0.0
3  0.550  0.360  0.289  0.232  0.155  0.081  0.034  0.007  0.006  0.0
4  0.775  0.517  0.423  0.348  0.275  0.154  0.085  0.027  0.016  0.0
5  0.792  0.690  0.564  0.355  0.280  0.202  0.102  0.033  0.014  0.0

In [48]:
X_train = feature_columns
Y_train = target_columns

In [49]:
test_df = final_df.loc[fr_test]

In [50]:
X_test = test_df[["Charge Density (%)", "Boron (B)", "Barium (Ba+2)", "Calcium (Ca+2)",	"Iron (Fe+2)", "Potassium (K+)", "Magnesium (Mg+2)", "Manganese (Mn+2)", "Sodium (Na+)", "Strontium (Sr+2)", "Zinc (Zn+2)", "Fluoride (F⁻)", "Chlorides (Cl-)",	"Nitrite (NO₂⁻)", "Bromide (Br⁻)", "Nitrate (NO₃⁻)", "Phosphate (PO₄³⁻)", "Sulfate (SO4-2)", "Bicarbonates (HCO3-)","Friction Reducer_A", "Friction Reducer_B","Friction Reducer_C", "Form_CO_ePAM","Form_Dry", 'Form_ePAM']]
Y_test = test_df[['500', '300', '250', '200', '150', '100', '50', '25', '12.5', '0']]

In [51]:
reg = model.fit(X_train, Y_train)
reg.score(X_train, Y_train)

1.0

In [52]:
Y_pred = model.predict(X_test)

In [53]:
print(Y_pred)

[[ 6.66489985e-01 -1.06202511e-01 -6.80712109e-02  1.41635059e-01
  -7.91528377e-02 -1.23435524e-01 -1.20876055e-01 -6.11881064e-02
  -3.50093312e-02  0.00000000e+00]
 [ 8.46356882e-01  3.76810921e-01  3.32950632e-01  2.55184458e-01
  -4.43928635e-02  7.12840433e-03 -8.53543125e-02 -4.26090173e-02
  -4.08590015e-02  0.00000000e+00]
 [ 2.79061851e+00  3.19987611e+00  2.74960280e+00  7.80898311e-01
  -1.16856903e-01  6.82906405e-01 -1.36709018e-02 -4.77487887e-02
  -1.71280556e-01  0.00000000e+00]
 [-1.49229525e+01 -1.14051844e+01 -9.81953820e+00 -7.45022128e+00
  -6.17813590e+00 -4.50779612e+00 -2.56221988e+00 -1.06529635e+00
  -3.52754751e-01  0.00000000e+00]
 [ 2.23426816e+00  1.13094607e-01  1.47797282e-01  1.06589597e+00
   9.06295088e-01  1.89653548e-01  2.09549487e-01  8.29250406e-02
   7.39416261e-02  0.00000000e+00]
 [ 2.42373467e+00  2.10082556e-01  2.33970483e-01  1.14471958e+00
   9.71961829e-01  2.30233836e-01  2.33772491e-01  9.15562744e-02
   7.65382539e-02  0.00000000e+00]]

In [54]:
Y_test.head()

      500    300    250    200    150    100     50     25   12.5      0
6   2.126  1.335  1.155  0.917  0.655  0.433  0.214  0.098  0.042  0.007
7   2.188  1.403  1.238  0.928  0.682  0.528  0.222  0.106  0.069  0.002
8   1.678  1.067  0.828  0.648  0.461  0.312  0.157  0.077  0.038  0.009
9   2.131  1.390  1.121  0.881  0.660  0.418  0.193  0.084  0.030  0.002
28  2.180  1.494  1.165  0.949  0.680  0.434  0.210  0.109  0.036  0.000

### Insight: 
A model trained exclusively on ePAM and CO-ePAM products was unable to predict a dry polymer product, suggesting that polymer form contributes significantly to curve behavior and that additional dry-polymer training data will be required.

# Model C (2nd iteration)

In [55]:
train_set = [1,2,3,4,5,6,7,8,9]
test_set = [10]

In [56]:
train_mask = final_df["Test_id"].isin(train_set)
test_mask = final_df["Test_id"].isin(test_set)

In [57]:
train_df = final_df.loc[train_mask]
test_df = final_df.loc[test_mask]

In [58]:
X_train = train_df[["Charge Density (%)",'TDS', "Boron (B)", "Barium (Ba+2)", "Calcium (Ca+2)",	"Iron (Fe+2)", "Potassium (K+)", "Magnesium (Mg+2)", "Manganese (Mn+2)", "Sodium (Na+)", "Strontium (Sr+2)", "Zinc (Zn+2)", "Fluoride (F⁻)", "Chlorides (Cl-)",	"Nitrite (NO₂⁻)", "Bromide (Br⁻)", "Nitrate (NO₃⁻)", "Phosphate (PO₄³⁻)", "Sulfate (SO4-2)", "Bicarbonates (HCO3-)"]]
Y_train = train_df[['500', '300', '250', '200', '150', '100', '50', '25', '12.5', '0']]

In [59]:
reg = model.fit(X_train, Y_train)
reg.score(X_train, Y_train)

1.0

In [60]:
X_test = test_df[["Charge Density (%)", 'TDS', "Boron (B)", "Barium (Ba+2)", "Calcium (Ca+2)",	"Iron (Fe+2)", "Potassium (K+)", "Magnesium (Mg+2)", "Manganese (Mn+2)", "Sodium (Na+)", "Strontium (Sr+2)", "Zinc (Zn+2)", "Fluoride (F⁻)", "Chlorides (Cl-)",	"Nitrite (NO₂⁻)", "Bromide (Br⁻)", "Nitrate (NO₃⁻)", "Phosphate (PO₄³⁻)", "Sulfate (SO4-2)", "Bicarbonates (HCO3-)"]]
Y_test = test_df[['500', '300', '250', '200', '150', '100', '50', '25', '12.5', '0']]

In [61]:
Y_pred = model.predict(X_test)
print(Y_pred)

[[-16.19084861 -14.48821218 -12.25085323  -8.24432738  -6.31854027
   -4.90099203  -2.78129983  -1.14650972  -0.14807244  -0.03048857]]

In [62]:
Y_test.head()

     500   300    250    200   150    100     50     25  12.5      0
9  2.131  1.39  1.121  0.881  0.66  0.418  0.193  0.084  0.03  0.002

In [63]:
print(model.coef_)

[[ 4.89169954e-05 -1.23893943e-04  5.06999422e-03  2.60683266e-04
  -7.12667408e-04  1.38920144e-03  5.85267438e-03 -3.86234695e-03
  -2.93561667e-05 -3.53127936e-05 -3.34491732e-03  8.64303998e-06
   0.00000000e+00  2.53690556e-04  0.00000000e+00  7.30338689e-03
   0.00000000e+00  0.00000000e+00 -1.19006414e-03 -2.01672468e-03]
 [ 9.84598390e-05 -3.32752979e-04  8.09642203e-03  4.33801511e-04
  -8.27837160e-04  2.69805487e-03  1.05875219e-02 -3.63000395e-03
  -4.01427292e-05 -1.00726335e-05 -3.64255050e-03  1.74005985e-05
   0.00000000e+00  5.50702747e-04  0.00000000e+00  6.42653623e-03
   0.00000000e+00  0.00000000e+00  4.11638967e-05 -1.77508713e-03]
 [ 7.87620132e-05 -2.56608961e-04  6.64150247e-03  3.53502246e-04
  -6.66245170e-04  2.16896866e-03  8.55977487e-03 -3.23753773e-03
  -3.35042345e-05 -1.14131485e-05 -3.16758144e-03  1.39400907e-05
   0.00000000e+00  4.26934799e-04  0.00000000e+00  5.81963597e-03
   0.00000000e+00  0.00000000e+00  1.12504203e-05 -1.50463423e-03]
 [ 2.60449070e-05 -1.04952854e-04  2.52486974e-03  1.31583116e-04
  -1.04032015e-04  7.24203031e-04  3.01814070e-03 -1.74539496e-03
  -1.43987220e-05 -1.39893055e-05 -1.56181655e-03  4.62785217e-06
   0.00000000e+00  1.74746186e-04  0.00000000e+00  3.29114891e-03
   0.00000000e+00  0.00000000e+00 -4.92688889e-04 -1.01092817e-03]
 [ 6.83335167e-06 -4.16945309e-05  1.18609971e-03  5.66413876e-05
  -3.87968302e-05  2.15118572e-04  1.08383081e-03 -1.50676533e-03
  -8.51285237e-06 -1.26889775e-05 -1.20262666e-03  1.24825470e-06
   0.00000000e+00  7.94292603e-05  0.00000000e+00  2.97897308e-03
   0.00000000e+00  0.00000000e+00 -5.80721485e-04 -7.64630706e-04]
 [ 1.52567020e-05 -4.40904865e-05  1.71354204e-03  8.52809136e-05
  -1.46783560e-04  4.45440398e-04  1.88465846e-03 -1.50392555e-03
  -1.01476784e-05 -8.92185156e-06 -1.28019765e-03  2.75525835e-06
   0.00000000e+00  8.02915997e-05  0.00000000e+00  2.91866422e-03
   0.00000000e+00  0.00000000e+00 -5.58248387e-05 -5.99447184e-04]
 [ 7.65247671e-06 -3.50915975e-05  8.24514295e-04  4.20843082e-05
  -6.70066515e-05  2.18695927e-04  9.32779541e-04 -6.70683608e-04
  -4.90277554e-06 -3.52849972e-06 -5.76554990e-04  1.36288500e-06
   0.00000000e+00  6.17189743e-05  0.00000000e+00  1.28086826e-03
   0.00000000e+00  0.00000000e+00 -1.93840054e-04 -3.29982764e-04]
 [ 2.84886025e-06 -1.55933893e-05  3.33088650e-04  1.66657251e-05
  -1.83675875e-05  8.30210392e-05  3.60662078e-04 -3.04589356e-04
  -2.04974890e-06 -2.05799149e-06 -2.57008252e-04  5.12955784e-07
   0.00000000e+00  2.70819251e-05  0.00000000e+00  5.90364708e-04
   0.00000000e+00  0.00000000e+00 -6.53810191e-05 -1.37801368e-04]
 [-5.57716053e-06  1.80700871e-05 -2.73173100e-04 -1.72407343e-05
   3.80232695e-05 -1.41531173e-04 -5.00759889e-04 -1.72524842e-04
   6.92574890e-07 -2.57466999e-06 -8.10714457e-05 -9.62166106e-07
   0.00000000e+00 -2.66366706e-05  0.00000000e+00  4.06968592e-04
   0.00000000e+00  0.00000000e+00 -3.24315425e-05 -2.16059565e-05]
 [ 8.67410160e-07 -3.89739469e-06  5.57284091e-05  3.25880435e-06
  -9.71694109e-06  2.28340715e-05  8.55927155e-05  1.93610682e-06
  -2.21604460e-07  7.78851410e-08 -5.96300515e-06  1.49762411e-07
   0.00000000e+00  6.59169262e-06  0.00000000e+00 -1.42286499e-05
   0.00000000e+00  0.00000000e+00 -9.86450818e-06 -3.73169312e-06]]

In [64]:
X_train.shape

(9, 20)

## Insight

The model failed to accurately predict the FR-C standard curve when trained using 20 features and 8 training samples. One possible explanation is that the ratio of features to training samples is too high, resulting in poor model generalization. Future testing will evaluate whether reducing the feature count while maintaining the same training data improves predictive performance.

### Training the model with less features

In [65]:
X_train = train_df[["Charge Density (%)",'TDS',"Form_CO_ePAM", "Form_Dry", "Form_ePAM"]]
Y_train = train_df[['500', '300', '250', '200', '150', '100', '50', '25', '12.5', '0']]

In [66]:
X_test = test_df[["Charge Density (%)", 'TDS', "Form_CO_ePAM", "Form_Dry", "Form_ePAM"]]
Y_test = test_df[['500', '300', '250', '200', '150', '100', '50', '25', '12.5', '0']]

In [67]:
reg = model.fit(X_train,Y_train)
reg.score(X_train,Y_train)

0.9143605017039196

In [68]:
Y_pred = model.predict(X_test)
print(Y_pred)

[[2.05615248 1.28886333 1.10189829 0.83911775 0.60570553 0.43193247
  0.19802617 0.09437104 0.04921727 0.00555582]]

In [69]:
Y_test.head()

     500   300    250    200   150    100     50     25  12.5      0
9  2.131  1.39  1.121  0.881  0.66  0.418  0.193  0.084  0.03  0.002

## Insight: 

Reducing the number of predictor variables improved the model's ability to approximate the laboratory-generated FR-C standard curve. While the predicted absorbance values remain higher than the measured values, the reduced-feature model generated a curve that more closely matched the overall shape and magnitude of the experimental data compared to the full-feature model. This result suggests that the original model may contain more predictor variables than can be effectively supported by the current training dataset, resulting in reduced predictive performance.

In [70]:
X_train = train_df[["Charge Density (%)",'TDS',"Form_CO_ePAM", "Form_Dry", "Form_ePAM"]]
Y_train = train_df[['300', '250', '200', '150', '100', '50', '25', '12.5', '0']]

In [71]:
X_test = test_df[["Charge Density (%)", 'TDS', "Form_CO_ePAM", "Form_Dry", "Form_ePAM"]]
Y_test = test_df[['300', '250', '200', '150', '100', '50', '25', '12.5', '0']]

In [72]:
reg = model.fit(X_train,Y_train)
reg.score(X_train,Y_train)

0.9108034825836735

In [73]:
Y_pred = model.predict(X_test)
print(Y_pred)

[[1.28886333 1.10189829 0.83911775 0.60570553 0.43193247 0.19802617
  0.09437104 0.04921727 0.00555582]]

In [74]:
X_train = train_df[["Charge Density (%)",'TDS',"DR (R+)", "Form_CO_ePAM", "Form_Dry", "Form_ePAM"]]
Y_train = train_df[['300', '250', '200', '150', '100', '50', '25', '12.5', '0']]

In [75]:
X_test = test_df[["Charge Density (%)", 'TDS', "DR (R+)", "Form_CO_ePAM", "Form_Dry", "Form_ePAM"]]
Y_test = test_df[['300', '250', '200', '150', '100', '50', '25', '12.5', '0']]

In [76]:
reg = model.fit(X_train,Y_train)
reg.score(X_train,Y_train)

0.9424303961749819

In [77]:
Y_pred = model.predict(X_test)
print(Y_pred)

[[1.32836329 1.14699042 0.88118237 0.63535561 0.4550409  0.20779969
  0.09989088 0.05358771 0.00508076]]

In [78]:
Y_test.head()

    300    250    200   150    100     50     25  12.5      0
9  1.39  1.121  0.881  0.66  0.418  0.193  0.084  0.03  0.002

In [79]:
from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(Y_test, Y_pred)
print(mae)

0.0229837583116441

## Model C (10 entries with 7 features)

In [80]:
train_set = [1,2,3,4,5,6,7,8,9,14]
test_set = [10]

In [81]:
train_mask = final_df["Test_id"].isin(train_set)
test_mask = final_df["Test_id"].isin(test_set)

In [82]:
train_df = final_df.loc[train_mask]
test_df = final_df.loc[test_mask]

In [83]:
X_train = train_df[["Charge Density (%)",'TDS',"DR (R+)", "Form_CO_ePAM", "Form_Dry", "Form_ePAM"]]
Y_train = train_df[['300', '250', '200', '150', '100', '50', '25', '12.5', '0']]

In [84]:
X_test = test_df[["Charge Density (%)", 'TDS', "DR (R+)", "Form_CO_ePAM", "Form_Dry", "Form_ePAM"]]
Y_test = test_df[['300', '250', '200', '150', '100', '50', '25', '12.5', '0']]

In [85]:
reg = model.fit(X_train,Y_train)
reg.score(X_train,Y_train)

0.9136865322490154

In [86]:
y_pred = model.predict(X_test)
print(y_pred)

[[1.31524043 1.11589629 0.90423261 0.64425005 0.45757039 0.20287038
  0.09615927 0.0451702  0.00357074]]

In [87]:
Y_test.head()

    300    250    200   150    100     50     25  12.5      0
9  1.39  1.121  0.881  0.66  0.418  0.193  0.084  0.03  0.002

In [88]:
mae = mean_absolute_error(Y_test, Y_pred)
print(mae)

0.0229837583116441

## Insight: 
Inclusion of an additional training curve did not materially affect model performance. The MAE remained approximately 0.022 absorbance units, suggesting the model may be approaching a stable solution for the current feature set and available training data.

# Model C (Slurry Form introduction to model)

In [89]:
train_set = [1,2,3,4,5,6,7,8,9,10,11,12,14]
test_set = [13]

In [90]:
train_mask = final_df["Test_id"].isin(train_set)
test_mask = final_df["Test_id"].isin(test_set)

In [91]:
train_df = final_df.loc[train_mask]
test_df = final_df.loc[test_mask]

In [92]:
X_train = train_df[["Charge Density (%)",'TDS',"DR (R+)", "Form_CO_ePAM", "Form_Dry", "Form_Slurry", "Form_ePAM"]]
Y_train = train_df[['300', '250', '200', '150', '100', '50', '25', '12.5', '0']]

In [93]:
X_test = test_df[["Charge Density (%)", 'TDS', "DR (R+)", "Form_CO_ePAM", "Form_Dry","Form_Slurry", "Form_ePAM"]]
Y_test = test_df[['300', '250', '200', '150', '100', '50', '25', '12.5', '0']]

In [94]:
reg = model.fit(X_train,Y_train)
reg.score(X_train,Y_train)

0.8992210362141014

In [95]:
Y_pred = model.predict(X_test)
print(Y_pred)

[[ 1.19678712e+00  1.05222029e+00  9.09670356e-01  6.08626743e-01
   3.97772369e-01  1.87526218e-01  9.57334060e-02  2.96344322e-02
  -8.35458031e-04]]

In [96]:
Y_test.head()

      300    250    200   150   100     50     25   12.5    0
12  1.038  0.896  0.707  0.52  0.34  0.176  0.102  0.022  0.0

In [97]:
mae = mean_absolute_error(Y_test,Y_pred)
print(mae)

0.07670439841342631

## Insight: 
The model was trained using FR-A, FR-B, FR-C, FR-E, and partial FR-D data, then tested on a held-out FR-D curve. The predicted curve reproduced the general decreasing standard curve shape, but produced a higher MAE of 0.076 compared with the previous FR-C holdout test (MAE ≈ 0.022). This suggests the model can approximate the curve trend, but prediction accuracy may vary by FR family and/or brine con

# Model D (26 Entries)

In [98]:
final_df['TDS'].describe()

count        40.000000
mean      58537.200000
std       57529.048235
min           5.000000
25%       11422.000000
50%       35971.500000
75%      113594.750000
max      167025.000000
Name: TDS, dtype: float64

In [99]:
final_df.head(20)

,Test_id,Charge Density (%),TDS,Boron (B),Barium (Ba+2),Calcium (Ca+2),Iron (Fe+2),Potassium (K+),Magnesium (Mg+2),Manganese (Mn+2),...,Friction Reducer_M,Friction Reducer_N,Friction Reducer_O,Friction Reducer_P,Friction Reducer_Q,Friction Reducer_R,Form_CO_ePAM,Form_Dry,Form_Slurry,Form_ePAM
0,1,32,5876,6.00,0.30,385.50,0.00,54.90,89.10,0.10,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,2,32,164384,25.70,4.40,8908.00,0.00,1082.00,940.40,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,3,32,89081,18.10,4.70,5255.00,0.00,469.80,549.30,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,4,30,11774,42.50,0.00,115.20,15.00,67.30,20.90,0.70,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,5,30,12993,36.40,0.00,158.80,12.70,55.70,25.80,0.70,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
5,6,30,15031,39.60,0.00,199.40,16.60,58.40,28.80,0.80,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
6,7,30,12657,73.38,2.43,71.23,1.87,84.78,16.99,0.30,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
7,8,30,15812,59.40,0.89,164.30,0.42,86.14,27.48,0.50,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
8,9,30,102804,29.40,2.24,3259.00,0.16,299.80,587.00,2.26,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
9,10,30,13069,87.74,0.52,102.30,1.45,76.14,14.12,0.07,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
10,11,30,23334,19.84,23.01,285.93,1.43,42.62,41.35,0.38,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
11,12,30,39767,16.59,107.82,366.25,3.73,99.48,78.22,0.52,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
12,13,30,16437,10.76,10.22,73.47,3.11,33.53,15.78,0.09,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
13,14,30,4677,0.00,1.64,58.26,0.23,116.60,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
14,15,32,32176,0.00,77.75,545.20,0.00,117.90,55.32,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
15,16,32,67505,0.00,182.70,1323.00,0.00,318.10,150.10,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
16,17,30,141057,27.80,2.04,2273.00,0.70,623.00,406.00,0.53,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
17,18,30,141057,27.80,2.04,2273.00,0.70,623.00,406.00,0.53,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
18,19,30,131855,28.00,2.02,1885.00,14.90,656.00,370.00,0.77,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
19,20,30,131855,28.00,2.02,1885.00,14.90,656.00,370.00,0.77,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [100]:
train_set = [1,2,3,4,5,6,7,8,9,10,11,12,12,14,15]
test_set = [16]

In [101]:
train_mask = final_df["Test_id"].isin(train_set)
test_mask = final_df["Test_id"].isin(test_set)

In [102]:
train_df = final_df.loc[train_mask]
test_df = final_df.loc[test_mask]

In [103]:
X_train = train_df[["Charge Density (%)",'TDS',"DR (R+)", "Form_CO_ePAM", "Form_Dry", "Form_Slurry", "Form_ePAM"]]
Y_train = train_df[['300', '250', '200', '150', '100', '50', '25', '12.5', '0']]

In [104]:
X_test = test_df[["Charge Density (%)", 'TDS', "DR (R+)", "Form_CO_ePAM", "Form_Dry","Form_Slurry", "Form_ePAM"]]
Y_test = test_df[['300', '250', '200', '150', '100', '50', '25', '12.5', '0']]

In [105]:
reg = model.fit(X_train,Y_train)
reg.score(X_train,Y_train)

0.9037749134395955

In [106]:
Y_pred = model.predict(X_test)
print(Y_pred)

[[1.63691886e+00 1.45601526e+00 1.06862350e+00 7.86211550e-01
  5.02297196e-01 2.90095175e-01 1.43822123e-01 5.51716440e-02
  1.34149701e-03]]

In [107]:
Y_test.head()

     300    250    200    150    100     50     25   12.5    0
15  2.07  1.885  1.439  0.952  0.665  0.301  0.146  0.056  0.0

In [108]:
mae = mean_absolute_error(Y_test,Y_pred)
print(mae)

0.17513179927194525

# Model C (40 entries)

In [122]:
def run_model(train_set, test_set):
    train_mask = final_df["Test_id"].isin(train_set)
    test_mask = final_df["Test_id"].isin(test_set)
    train_df = final_df.loc[train_mask]
    test_df = final_df.loc[test_mask]
    X_train = train_df[["Charge Density (%)",'TDS',"DR (R+)", "Form_CO_ePAM", "Form_Dry", "Form_Slurry", "Form_ePAM"]]
    Y_train = train_df[['300', '250', '200', '150', '100', '50', '25', '12.5', '0']]
    X_test = test_df[["Charge Density (%)", 'TDS', "DR (R+)", "Form_CO_ePAM", "Form_Dry","Form_Slurry", "Form_ePAM"]]
    Y_test = test_df[['300', '250', '200', '150', '100', '50', '25', '12.5', '0']]
    reg = model.fit(X_train,Y_train)
    reg_score = reg.score(X_train,Y_train)
    Y_pred = model.predict(X_test)
    mae = mean_absolute_error(Y_test,Y_pred)
    return print('y_pred:', Y_pred,'\nY_test:', Y_test, "\nMAE:", mae, "\nreg_score", reg_score)

In [123]:
train_set = [1,2,3,4,5,6,7,8,9,10,11,12,12,14,15]
test_set = [16]

results = run_model(train_set, test_set)

y_pred: [[1.63691886e+00 1.45601526e+00 1.06862350e+00 7.86211550e-01
  5.02297196e-01 2.90095175e-01 1.43822123e-01 5.51716440e-02
  1.34149701e-03]]
Y_test:      300    250    200    150    100     50     25   12.5    0
15  2.07  1.885  1.439  0.952  0.665  0.301  0.146  0.056  0.0
MAE: 0.17513179927194525
reg_score 0.9037749134395955

In [124]:
train_set = [1,2,3,4,5,6,7,8,9,10,11,12,12,14,16]
test_set = [15]

results= run_model(train_set, test_set)

y_pred: [[ 2.12208114e+00  1.94098474e+00  1.48137650e+00  9.83788450e-01
   6.89702804e-01  3.06904825e-01  1.49177877e-01  5.58283560e-02
  -1.34149701e-03]]
Y_test:       300    250    200    150    100     50     25   12.5    0
14  1.689  1.512  1.111  0.818  0.527  0.296  0.147  0.055  0.0
MAE: 0.1751317992832027
reg_score 0.9071889065083969