In [1]:
import sys
!{sys.executable} -m pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\karwi\appdata\local\programs\python\python313\lib\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in c:\users\karwi\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (2.4.3)
Requirement already satisfied: scipy>=1.10.0 in c:\users\karwi\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in c:\users\karwi\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\karwi\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (3.6.0)

[notice] A new release of pip is available: 24.3.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [7]:
import pandas as pd
import matplotlib as pt
import sklearn

In [8]:
master_sheet = pd.read_csv("PAM ML Master Sheet.csv")

In [9]:
master_sheet.head(10)

,Test_id,Friction Reducer,Form,Charge Density (%),TDS,Boron (B),Barium (Ba+2),Calcium (Ca+2),Iron (Fe+2),Potassium (K+),...,300,250,200,150,100,50,25,12.5,0,R^2
0,1.0,A,CO_ePAM,32.0,5876.0,6.00,0.30000,385.500,0.0000,54.900,...,1.725,1.470,1.328,0.899,0.595,0.293,0.139,0.050,0.000,0.9800
1,2.0,A,CO_ePAM,32.0,164384.0,25.70,4.40000,8908.000,0.0000,1082.000,...,1.790,1.530,1.470,1.004,0.660,0.334,0.151,0.065,0.000,0.9500
2,3.0,A,CO_ePAM,32.0,89081.0,18.10,4.70000,5255.000,0.0000,469.800,...,1.802,1.514,1.414,0.952,0.644,0.323,0.169,0.077,0.000,0.9600
3,4.0,B,ePAM,30.0,11774.0,42.50,0.00000,115.200,15.0000,67.300,...,0.360,0.289,0.232,0.155,0.081,0.034,0.007,0.006,0.000,0.9900
4,5.0,B,ePAM,30.0,12993.0,36.40,0.00000,158.800,12.7000,55.700,...,0.517,0.423,0.348,0.275,0.154,0.085,0.027,0.016,0.000,0.9900
5,6.0,B,ePAM,30.0,15031.0,39.60,0.00000,199.400,16.6000,58.400,...,0.690,0.564,0.355,0.280,0.202,0.102,0.033,0.014,0.000,0.9400
6,7.0,C,Dry,30.0,12657.0,73.38,2.43020,71.234,1.8672,84.778,...,1.335,1.155,0.917,0.655,0.433,0.214,0.098,0.042,0.007,0.9977
7,8.0,C,Dry,30.0,15812.0,59.40,0.88975,164.300,0.4240,86.135,...,1.403,1.238,0.928,0.682,0.528,0.222,0.106,0.069,0.002,0.9953
8,9.0,C,Dry,30.0,102804.0,29.40,2.23700,3259.000,0.1610,299.800,...,1.067,0.828,0.648,0.461,0.312,0.157,0.077,0.038,0.009,0.9976
9,10.0,C,Dry,30.0,13069.0,87.74,0.51880,102.300,1.4510,76.138,...,1.390,1.121,0.881,0.660,0.418,0.193,0.084,0.030,0.002,0.9973

In [10]:
master_sheet.dtypes

Test_id                 float64
Friction Reducer            str
Form                        str
Charge Density (%)      float64
TDS                     float64
Boron (B)               float64
Barium (Ba+2)           float64
Calcium (Ca+2)          float64
Iron (Fe+2)             float64
Potassium (K+)          float64
Magnesium (Mg+2)        float64
Manganese (Mn+2)        float64
Sodium (Na+)            float64
Strontium (Sr+2)        float64
Zinc (Zn+2)             float64
Fluoride (F⁻)           float64
Chlorides (Cl-)         float64
Nitrite (NO₂⁻)          float64
Bromide (Br⁻)           float64
Nitrate (NO₃⁻)          float64
Phosphate (PO₄³⁻)       float64
Sulfate (SO4-2)         float64
Bicarbonates (HCO3-)    float64
Carbonates (CO3-2)      float64
DR (R+)                 float64
500                     float64
300                     float64
250                     float64
200                     float64
150                     float64
100                     float64
50                      float64
25                      float64
12.5                    float64
0                       float64
R^2                     float64
dtype: object

In [6]:
numeric_cols =['TDS','Boron (B)', 'Barium (Ba+2)',	'Calcium (Ca+2)','Iron (Fe+2)','Potassium (K+)','Magnesium (Mg+2)','Manganese (Mn+2)','Strontium (Sr+2)','Zinc (Zn+2)', 'Bromide (Br⁻)','Sulfate (SO4-2)', '500','300',	'250', '200',	'150',	'100',	'50',	'25',	'12,5',	'0', 'R^2']
for col in numeric_cols:
    master_sheet[col] = master_sheet[col].str.replace(',','.')

AttributeError: Can only use .str accessor with string values, not floating

In [ ]:
numeric_cols = ['Charge Density (%)',
                'TDS','Boron (B)', 'Barium (Ba+2)',	'Calcium (Ca+2)','Iron (Fe+2)','Potassium (K+)','Magnesium (Mg+2)','Manganese (Mn+2)','Sodium (Na+)','Strontium (Sr+2)','Zinc (Zn+2)','Fluoride (F⁻)', 'Chlorides (Cl-)', 'Nitrite (NO₂⁻)', 'Bromide (Br⁻)', 'Nitrate (NO₃⁻)', 'Phosphate (PO₄³⁻)', 'Sulfate (SO4-2)', 'Bicarbonates (HCO3-)', '500','300',	'250', '200',	'150',	'100',	'50',	'25',	'12,5',	'0', 'R^2']
for col in numeric_cols:
    master_sheet[col] = pd.to_numeric(master_sheet[col], errors='coerce')

KeyError: '12,5'

In [11]:
master_sheet.info()

<class 'pandas.DataFrame'>
RangeIndex: 45 entries, 0 to 44
Data columns (total 36 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Test_id               14 non-null     float64
 1   Friction Reducer      15 non-null     str
 2   Form                  14 non-null     str
 3   Charge Density (%)    14 non-null     float64
 4   TDS                   14 non-null     float64
 5   Boron (B)             14 non-null     float64
 6   Barium (Ba+2)         14 non-null     float64
 7   Calcium (Ca+2)        14 non-null     float64
 8   Iron (Fe+2)           14 non-null     float64
 9   Potassium (K+)        14 non-null     float64
 10  Magnesium (Mg+2)      14 non-null     float64
 11  Manganese (Mn+2)      14 non-null     float64
 12  Sodium (Na+)          14 non-null     float64
 13  Strontium (Sr+2)      14 non-null     float64
 14  Zinc (Zn+2)           14 non-null     float64
 15  Fluoride (F⁻)         14 non-null     float64
 16  Chlorides (Cl-)       14 non-null     float64
 17  Nitrite (NO₂⁻)        14 non-null     float64
 18  Bromide (Br⁻)         14 non-null     float64
 19  Nitrate (NO₃⁻)        14 non-null     float64
 20  Phosphate (PO₄³⁻)     14 non-null     float64
 21  Sulfate (SO4-2)       14 non-null     float64
 22  Bicarbonates (HCO3-)  14 non-null     float64
 23  Carbonates (CO3-2)    14 non-null     float64
 24  DR (R+)               14 non-null     float64
 25  500                   14 non-null     float64
 26  300                   14 non-null     float64
 27  250                   14 non-null     float64
 28  200                   14 non-null     float64
 29  150                   14 non-null     float64
 30  100                   14 non-null     float64
 31  50                    14 non-null     float64
 32  25                    14 non-null     float64
 33  12.5                  14 non-null     float64
 34  0                     14 non-null     float64
 35  R^2                   14 non-null     float64
dtypes: float64(34), str(2)
memory usage: 12.8 KB

In [13]:
master_sheet.head(10)

,Test_id,Friction Reducer,Form,Charge Density (%),TDS,Boron (B),Barium (Ba+2),Calcium (Ca+2),Iron (Fe+2),Potassium (K+),...,300,250,200,150,100,50,25,12.5,0,R^2
0,1.0,A,CO_ePAM,32.0,5876.0,6.00,0.30000,385.500,0.0000,54.900,...,1.725,1.470,1.328,0.899,0.595,0.293,0.139,0.050,0.000,0.9800
1,2.0,A,CO_ePAM,32.0,164384.0,25.70,4.40000,8908.000,0.0000,1082.000,...,1.790,1.530,1.470,1.004,0.660,0.334,0.151,0.065,0.000,0.9500
2,3.0,A,CO_ePAM,32.0,89081.0,18.10,4.70000,5255.000,0.0000,469.800,...,1.802,1.514,1.414,0.952,0.644,0.323,0.169,0.077,0.000,0.9600
3,4.0,B,ePAM,30.0,11774.0,42.50,0.00000,115.200,15.0000,67.300,...,0.360,0.289,0.232,0.155,0.081,0.034,0.007,0.006,0.000,0.9900
4,5.0,B,ePAM,30.0,12993.0,36.40,0.00000,158.800,12.7000,55.700,...,0.517,0.423,0.348,0.275,0.154,0.085,0.027,0.016,0.000,0.9900
5,6.0,B,ePAM,30.0,15031.0,39.60,0.00000,199.400,16.6000,58.400,...,0.690,0.564,0.355,0.280,0.202,0.102,0.033,0.014,0.000,0.9400
6,7.0,C,Dry,30.0,12657.0,73.38,2.43020,71.234,1.8672,84.778,...,1.335,1.155,0.917,0.655,0.433,0.214,0.098,0.042,0.007,0.9977
7,8.0,C,Dry,30.0,15812.0,59.40,0.88975,164.300,0.4240,86.135,...,1.403,1.238,0.928,0.682,0.528,0.222,0.106,0.069,0.002,0.9953
8,9.0,C,Dry,30.0,102804.0,29.40,2.23700,3259.000,0.1610,299.800,...,1.067,0.828,0.648,0.461,0.312,0.157,0.077,0.038,0.009,0.9976
9,10.0,C,Dry,30.0,13069.0,87.74,0.51880,102.300,1.4510,76.138,...,1.390,1.121,0.881,0.660,0.418,0.193,0.084,0.030,0.002,0.9973

In [14]:
master_sheet.notna().value_counts()

Test_id  Friction Reducer  Form   Charge Density (%)  TDS    Boron (B)  Barium (Ba+2)  Calcium (Ca+2)  Iron (Fe+2)  Potassium (K+)  Magnesium (Mg+2)  Manganese (Mn+2)  Sodium (Na+)  Strontium (Sr+2)  Zinc (Zn+2)  Fluoride (F⁻)  Chlorides (Cl-)  Nitrite (NO₂⁻)  Bromide (Br⁻)  Nitrate (NO₃⁻)  Phosphate (PO₄³⁻)  Sulfate (SO4-2)  Bicarbonates (HCO3-)  Carbonates (CO3-2)  DR (R+)  500    300    250    200    150    100    50     25     12.5   0      R^2
False    False             False  False               False  False      False          False           False        False           False             False             False         False             False        False          False            False           False          False           False              False            False                 False               False    False  False  False  False  False  False  False  False  False  False  False    30
True     True              True   True                True   True       True           True            True         True            True              True              True          True              True         True           True             True            True           True            True               True             True                  True                True     True   True   True   True   True   True   True   True   True   True   True     14
False    True              False  False               False  False      False          False           False        False           False             False             False         False             False        False          False            False           False          False           False              False            False                 False               False    False  False  False  False  False  False  False  False  False  False  False     1
Name: count, dtype: int64

# Model A

In [16]:
from sklearn.linear_model import LinearRegression

In [17]:
model = LinearRegression()

In [18]:
feature_columns =  master_sheet[["TDS", "Boron (B)", "Barium (Ba+2)", "Calcium (Ca+2)",	"Iron (Fe+2)", "Potassium (K+)", "Magnesium (Mg+2)", "Manganese (Mn+2)", "Sodium (Na+)", "Strontium (Sr+2)", "Zinc (Zn+2)", "Fluoride (F⁻)", "Chlorides (Cl-)",	"Nitrite (NO₂⁻)", "Bromide (Br⁻)", "Nitrate (NO₃⁻)", "Phosphate (PO₄³⁻)", "Sulfate (SO4-2)", "Bicarbonates (HCO3-)", "DR (R+)"]]

In [19]:
feature_columns.head(6)

,TDS,Boron (B),Barium (Ba+2),Calcium (Ca+2),Iron (Fe+2),Potassium (K+),Magnesium (Mg+2),Manganese (Mn+2),Sodium (Na+),Strontium (Sr+2),Zinc (Zn+2),Fluoride (F⁻),Chlorides (Cl-),Nitrite (NO₂⁻),Bromide (Br⁻),Nitrate (NO₃⁻),Phosphate (PO₄³⁻),Sulfate (SO4-2),Bicarbonates (HCO3-),DR (R+)
0,5876.0,6.0,0.3,385.5,0.0,54.9,89.1,0.1,1527.0,10.7,0.46,0.0,2855.0,0.0,26.2,0.0,0.0,904.7,17.0,0.17
1,164384.0,25.7,4.4,8908.0,0.0,1082.0,940.4,0.0,54790.0,279.8,0.43,0.0,96414.0,0.0,419.4,0.0,0.0,1151.9,369.0,0.12
2,89081.0,18.1,4.7,5255.0,0.0,469.8,549.3,0.0,25960.0,116.5,0.63,0.0,54754.0,0.0,280.1,0.0,0.0,1304.2,369.0,0.10
3,11774.0,42.5,0.0,115.2,15.0,67.3,20.9,0.7,39587.0,11.5,0.00,0.0,5518.5,0.0,154.8,0.0,0.0,593.6,1276.0,0.02
4,12993.0,36.4,0.0,158.8,12.7,55.7,25.8,0.7,44211.0,13.6,0.00,0.0,6381.4,0.0,180.4,0.0,0.0,549.5,1157.0,0.03
5,15031.0,39.6,0.0,199.4,16.6,58.4,28.8,0.8,50428.0,14.5,0.00,0.0,7647.5,0.0,216.0,0.0,0.0,592.0,1174.6,0.03

In [21]:
target_columns = master_sheet[["500", "300", "250", "200", "150", "100", "50", "25", "12.5", "0"]]

In [ ]:
target_columns.head()
target_columns.shape

(3, 10)

In [22]:
X_train = feature_columns.loc[(feature_columns['TDS'] == 5876.0	) | (feature_columns['TDS']==164384.0)]

In [23]:
Y_train = target_columns.loc[X_train.index]

In [24]:
Y_train.head()

     500    300   250    200    150    100     50     25   12.5    0
0  2.447  1.725  1.47  1.328  0.899  0.595  0.293  0.139  0.050  0.0
1  2.381  1.790  1.53  1.470  1.004  0.660  0.334  0.151  0.065  0.0

In [25]:
X_test = feature_columns.loc[(feature_columns['TDS'] == 89081.0)]
Y_test = target_columns.loc[X_test.index]

In [26]:
reg = model.fit(X_train, Y_train)

reg.score(X_train,Y_train)

1.0

In [27]:
Y_pred = model.predict(X_test)

In [28]:
print(Y_pred)

[[2.41221787 1.75925513 1.50162012 1.40283428 0.95433521 0.62925513
  0.31460708 0.14532402 0.05790503 0.        ]]

In [29]:
Y_test.head()

   500    300    250    200    150    100     50     25   12.5    0
2  2.0  1.802  1.514  1.414  0.952  0.644  0.323  0.169  0.077  0.0

# Model B Test

In [30]:
model_b = master_sheet

In [31]:
model_b.drop(columns=['500'])

,Test_id,Friction Reducer,Form,Charge Density (%),TDS,Boron (B),Barium (Ba+2),Calcium (Ca+2),Iron (Fe+2),Potassium (K+),...,300,250,200,150,100,50,25,12.5,0,R^2
0,1.0,A,CO_ePAM,32.0,5876.0,6.000,0.30000,385.500,0.0000,54.900,...,1.725,1.470,1.328,0.899,0.595,0.293,0.139,0.050,0.000,0.9800
1,2.0,A,CO_ePAM,32.0,164384.0,25.700,4.40000,8908.000,0.0000,1082.000,...,1.790,1.530,1.470,1.004,0.660,0.334,0.151,0.065,0.000,0.9500
2,3.0,A,CO_ePAM,32.0,89081.0,18.100,4.70000,5255.000,0.0000,469.800,...,1.802,1.514,1.414,0.952,0.644,0.323,0.169,0.077,0.000,0.9600
3,4.0,B,ePAM,30.0,11774.0,42.500,0.00000,115.200,15.0000,67.300,...,0.360,0.289,0.232,0.155,0.081,0.034,0.007,0.006,0.000,0.9900
4,5.0,B,ePAM,30.0,12993.0,36.400,0.00000,158.800,12.7000,55.700,...,0.517,0.423,0.348,0.275,0.154,0.085,0.027,0.016,0.000,0.9900
5,6.0,B,ePAM,30.0,15031.0,39.600,0.00000,199.400,16.6000,58.400,...,0.690,0.564,0.355,0.280,0.202,0.102,0.033,0.014,0.000,0.9400
6,7.0,C,Dry,30.0,12657.0,73.380,2.43020,71.234,1.8672,84.778,...,1.335,1.155,0.917,0.655,0.433,0.214,0.098,0.042,0.007,0.9977
7,8.0,C,Dry,30.0,15812.0,59.400,0.88975,164.300,0.4240,86.135,...,1.403,1.238,0.928,0.682,0.528,0.222,0.106,0.069,0.002,0.9953
8,9.0,C,Dry,30.0,102804.0,29.400,2.23700,3259.000,0.1610,299.800,...,1.067,0.828,0.648,0.461,0.312,0.157,0.077,0.038,0.009,0.9976
9,10.0,C,Dry,30.0,13069.0,87.740,0.51880,102.300,1.4510,76.138,...,1.390,1.121,0.881,0.660,0.418,0.193,0.084,0.030,0.002,0.9973
10,11.0,D,Slurry,30.0,23334.0,19.844,23.00900,285.925,1.4320,42.622,...,1.070,0.877,0.717,0.522,0.348,0.166,0.078,0.021,0.000,0.9986
11,12.0,D,Slurry,30.0,39767.0,16.590,107.82000,366.250,3.7265,99.480,...,1.248,1.147,1.032,0.644,0.409,0.197,0.107,0.036,0.000,0.9868
12,13.0,D,Slurry,30.0,16437.0,10.760,10.22000,73.470,3.1120,33.530,...,1.038,0.896,0.707,0.520,0.340,0.176,0.102,0.022,0.000,0.9994
13,14.0,E,Dry,30.0,4677.0,0.000,1.63500,58.260,0.2326,116.600,...,1.292,1.054,0.960,0.667,0.466,0.192,0.088,0.026,0.000,0.9921
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,NaN,"15,812",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
feature_columns =  model_b[["TDS", "Boron (B)", "Barium (Ba+2)", "Calcium (Ca+2)",	"Iron (Fe+2)", "Potassium (K+)", "Magnesium (Mg+2)", "Manganese (Mn+2)", "Sodium (Na+)", "Strontium (Sr+2)", "Zinc (Zn+2)", "Fluoride (F⁻)", "Chlorides (Cl-)",	"Nitrite (NO₂⁻)", "Bromide (Br⁻)", "Nitrate (NO₃⁻)", "Phosphate (PO₄³⁻)", "Sulfate (SO4-2)", "Bicarbonates (HCO3-)"]]

In [35]:
target_columns = model_b[["300", "250", "200", "150", "100", "50", "25", "12.5", "0"]]

In [36]:
X_train = feature_columns.loc[(feature_columns['TDS'] == 5876.0	) | (feature_columns['TDS']==164384.0)]

In [37]:
Y_train = target_columns.loc[X_train.index]

In [38]:
X_test = feature_columns.loc[(feature_columns['TDS'] == 89081.0)]

In [39]:
Y_test = target_columns.loc[X_test.index]

In [40]:
reg = model.fit(X_train, Y_train)
reg.score(X_train, Y_train)

1.0

In [41]:
Y_pred = model.predict(X_test)

In [42]:
print(Y_pred)

[[1.75925513 1.50162012 1.40283428 0.95433521 0.62925513 0.31460708
  0.14532402 0.05790503 0.        ]]

## Insight:
A preliminary multi-output linear regression model was trained using standard curve data from two brines (5k and 164k TDS) and tested against an intermediate brine (~89k TDS). The model successfully reproduced the overall shape of the standard curve and generated absorbance predictions that were generally close to the observed values. The largest deviation occurred at the 500 ppm calibration point, which is also associated with reduced standard curve linearity (R² < 0.99) in laboratory measurements. Removing the 500 ppm point improved standard curve performance and suggests that the upper calibration range may contribute disproportionate variability.

# Model A (14 Entries)